import { Language } from './types';

export const translations = {
  it: {
    title: "Sfide VS",
    subtitle: "Genera e simula scenari di scontro folli con contenuti in tempo reale estratti da Wikipedia.",
    btnGenerate: "Genera Nuova Sfida",
    btnAdd: "Aggiungi Sfidante",
    btnReset: "Azzera Gioco",
    toggleTerrain: "Includi Terreno",
    toggleEquip: "Usa Equipaggiamento",
    terrainTitle: "Terreno dello Scontro",
    winnerBadge: "Vincitore",
    btnWinner: "Dichiara Vincitore",
    notesPlaceholder: "Aggiungi dettagli, tattiche, punti deboli o strategie di scontro...",
    editHint: "✍️ Clicca sul testo della domanda per modificarla liberamente!",
    winnerBtnText: "VINCITORE!",
    loadingError: "Impossibile caricare la descrizione live da Wikipedia.",
    rerollTooltip: "Riprova con un altro",
    equipCount: "Oggetti per sfidante (1-3)",
    declareLabel: "Scegli chi vince!",
    loading: "Caricamento...",
    notesLabel: "Strategie & Appunti",
    toggleRandomizer: "Total Randomizer 🎲",
    randomizerTooltip: "Genera tutto in tempo reale con Wikipedia totalmente a caso! Minimizza i tempi di ricerca tramite prefetching e caching.",
    btnAiWinner: "Decreta Vincitore (IA)",
    aiWinnerLoading: "L'IA sta decidendo...",
    aiExplainTitle: "Verdetto dell'I.A.",
    btnRandomQuestion: "Randomizza Domanda",
    randomQuestionTooltip: "Cambia la domanda o lo scenario di scontro in modo casuale!"
  },
  en: {
    title: "VS Battle Generator",
    subtitle: "Generate and simulate crazy battle scenarios using real-time content from Wikipedia.",
    btnGenerate: "Generate New Challenge",
    btnAdd: "Add Contender",
    btnReset: "Reset Game",
    toggleTerrain: "Include Terrain",
    toggleEquip: "Use Equipment",
    terrainTitle: "Clash Terrain",
    winnerBadge: "Winner",
    btnWinner: "Declare Winner",
    notesPlaceholder: "Add battle details, tactics, weaknesses or masterplans...",
    editHint: "✍️ Click on the question text to edit it freely!",
    winnerBtnText: "WINNER!",
    loadingError: "Unable to load live description from Wikipedia.",
    rerollTooltip: "Reroll this element",
    equipCount: "Items per contender (1-3)",
    declareLabel: "Choose the winner!",
    loading: "Loading...",
    notesLabel: "Tactics & Notes",
    toggleRandomizer: "Total Randomizer 🎲",
    randomizerTooltip: "Generates everything in real-time from random Wikipedia articles! Uses parallel prefetching and caching to minimize search times.",
    btnAiWinner: "Decree Winner (AI)",
    aiWinnerLoading: "AI is deciding...",
    aiExplainTitle: "A.I. Verdict",
    btnRandomQuestion: "Randomize Question",
    randomQuestionTooltip: "Randomly cycle to another scenario or comparison question!"
  }
};

export const questions: Record<Language, string[]> = {
  it: [
    "Chi è più forte in uno scontro diretto?", 
    "Chi vincerebbe a una gara di cucina?",
    "Chi sopravvivrebbe più a lungo su un'isola deserta?", 
    "Chi vincerebbe in una gara di ballo?",
    "Chi sarebbe il migliore a gestire un'azienda?", 
    "Chi vincerebbe a nascondino?",
    "Chi è il più intelligente tra loro?", 
    "Chi vincerebbe in un dibattito politico?",
    "Chi farebbe più amicizia a una festa?", 
    "Chi riuscirebbe a montare un mobile IKEA più velocemente?",
    "Chi racconterebbe la barzelletta più divertente?", 
    "Chi perderebbe prima la pazienza in mezzo al traffico?",
    "Chi vincerebbe una maratona olimpica?", 
    "Chi è il più bravo a cantare sotto la doccia?",
    "Chi sopravvivrebbe più a lungo a un'apocalisse zombie?", 
    "Chi vincerebbe una partita a scacchi?",
    "Chi verrebbe scelto come Presidente della Terra?", 
    "Chi riuscirebbe a vendere sabbia nel deserto?",
    "Chi verrebbe arrestato per primo in una rapina?", 
    "Chi è il più pigro della situazione?",
    "Chi piangerebbe guardando un film drammatico?", 
    "Chi è il più bravo a tenere un segreto?",
    "Chi accumulerebbe più debiti sulla carta di credito?", 
    "Chi vincerebbe un torneo di sasso-carta-forbice?",
    "Chi riuscirebbe a addomesticare un drago?", 
    "Chi dimenticherebbe le chiavi di casa più spesso?",
    "Chi farebbe la figura peggiore a un primo appuntamento?", 
    "Chi finirebbe per primo in un reality show?",
    "Chi è il re dei meme?", 
    "Chi farebbe il caffè più buono del mondo?",
    "Chi vincerebbe una battaglia rap?", 
    "Chi mangerebbe più fette di pizza in 10 minuti?",
    "Chi si perderebbe usando Google Maps?", 
    "Chi scoprirebbe per primo il segreto dell'immortalità?",
    "Chi diventerebbe un influencer da milioni di follower?", 
    "Chi vincerebbe una gara di sguardi senza battere ciglio?",
    "Chi verrebbe rapito dagli alieni per primo?", 
    "Chi sopravvivrebbe a una caduta libera in stile cartone animato?",
    "Chi spenderebbe tutto il suo budget in cose inutili?", 
    "Chi vincerebbe in una rissa da bar?",
    "Chi passerebbe un esame universitario senza aver studiato?", 
    "Chi spaventerebbe i fantasmi in una casa infestata?",
    "Chi diventerebbe il capo di una setta misteriosa?", 
    "Chi è il più fortunato del gruppo?",
    "Chi vincerebbe a un gioco da tavolo strategico?", 
    "Chi sarebbe il peggior babysitter del mondo?",
    "Chi verrebbe espulso da un museo per aver toccato le opere?", 
    "Chi riuscirebbe a nuotare più velocemente controcorrente?",
    "Chi vincerebbe un match di boxe con le regole ufficiali?", 
    "Chi scalerebbe l'Everest in pantaloncini corti?",
    "Chi creerebbe la teoria del complotto più folle?", 
    "Chi vincerebbe un torneo di braccio di ferro?",
    "Chi sarebbe il miglior capitano di una nave pirata?", 
    "Chi verrebbe bannato da internet per primo?",
    "Chi riuscirebbe a fare il miglior barbecue della domenica?", 
    "Chi dormirebbe durante un terremoto?",
    "Chi è più probabile che diventi un supereroe?", 
    "Chi è più probabile che diventi un supercattivo?",
    "Chi vincerebbe una gara di corsa nei sacchi?", 
    "Chi risolverebbe un mistero degno di Sherlock Holmes?",
    "Chi verrebbe truffato più facilmente da una mail sospetta?", 
    "Chi è il più bravo a contrattare al mercato delle pulci?",
    "Chi vincerebbe una gara di barzellette squallide?", 
    "Chi diventerebbe il re del karaoke?",
    "Chi riuscirebbe a scappare da una prigione di massima sicurezza?", 
    "Chi scriverebbe il romanzo fantasy più venduto di sempre?",
    "Chi finirebbe sulla copertina di Time Magazine?", 
    "Chi sarebbe il primo a gridare 'Aiuto!' vedendo un ragno?",
    "Chi riuscirebbe a convincere un gatto ad obbedirgli?", 
    "Chi vincerebbe una partita a poker bluffando?",
    "Chi è il più bravo a fare i regali di Natale?", 
    "Chi sopravvivrebbe nel Sahara solo con una bottiglia d'acqua?",
    "Chi farebbe i migliori cocktail a un open bar?", 
    "Chi inventerebbe l'app del secolo?",
    "Chi vincerebbe un campionato mondiale di videogiochi?", 
    "Chi verrebbe scambiato per una celebrità per strada?",
    "Chi mangerebbe il peperoncino più piccante senza fare una piega?", 
    "Chi è il peggiore a guidare l'auto?",
    "Chi passerebbe ore a spiegarti perché la sua saga preferita è la migliore?", 
    "Chi vincerebbe una gara a chi urla più forte?",
    "Chi verrebbe espulso da un cinema per aver spoilerato il finale?", 
    "Chi riuscirebbe a riparare un motore con scotch e gomma da masticare?",
    "Chi farebbe la miglior imitazione dell'altro?", 
    "Chi passerebbe la notte di Halloween nel cimitero senza paura?",
    "Chi vincerebbe un duello medievale con la giostra dei cavalli?", 
    "Chi verrebbe eletto sindaco della tua città?",
    "Chi finirebbe per primo le scorte di cibo in un bunker?", 
    "Chi diventerebbe una leggenda metropolitana?",
    "Chi vincerebbe una battaglia con i cuscini?", 
    "Chi è il più ritardatario del gruppo?",
    "Chi riuscirebbe a camminare sui carboni ardenti?", 
    "Chi verrebbe incoronato re o regina della giungla?",
    "Chi vincerebbe una gara di spelling?", 
    "Chi farebbe la proposta di matrimonio più assurda?",
    "Chi verrebbe scelto per una missione spaziale senza ritorno?", 
    "Chi passerebbe ore allo specchio a sistemarsi?",
    "Chi vincerebbe una maratona di serie TV di 48 ore di fila?", 
    "Chi distruggerebbe un'opera d'arte moderna scambiandola per spazzatura?",
    "Chi farebbe la spesa dimenticando la metà delle cose da comprare?", 
    "Chi diventerebbe il miglior detective privato della città?",
    "Chi riuscirebbe a farsi offrire la cena da uno sconosciuto?", 
    "Chi vincerebbe una battaglia di palle di neve?",
    "Chi sarebbe il peggior concorrente in un quiz televisivo?", 
    "Chi verrebbe salvato per primo in caso di naufragio?",
    "Chi riuscirebbe a fare silenzio per 24 ore di fila?"
  ],
  en: [
    "Who is stronger in a direct fight?", 
    "Who would win a cooking competition?",
    "Who would survive the longest on a desert island?", 
    "Who would win a dance-off?",
    "Who would be the best at running a company?", 
    "Who would win at hide and seek?",
    "Who is the smartest among them?", 
    "Who would win in a political debate?",
    "Who would make more friends at a party?", 
    "Who could assemble an IKEA furniture fastest?",
    "Who would tell the funniest joke?", 
    "Who would lose their patience first in traffic?",
    "Who would win an Olympic marathon?", 
    "Who is the best at singing in the shower?",
    "Who would survive the longest in a zombie apocalypse?", 
    "Who would win a chess match?",
    "Who would be chosen as President of the Earth?", 
    "Who could sell sand in the desert?",
    "Who would get arrested first in a robbery?", 
    "Who is the laziest?",
    "Who would cry watching a dramatic movie?", 
    "Who is the best at keeping a secret?",
    "Who would accumulate the most credit card debt?", 
    "Who would win a rock-paper-scissors tournament?",
    "Who could tame a dragon?", 
    "Who would forget their house keys most often?",
    "Who would have the worst first date?", 
    "Who would end up on a reality TV show first?",
    "Who is the king of memes?", 
    "Who would make the best coffee in the world?",
    "Who would win a rap battle?", 
    "Who could eat more pizza slices in 10 minutes?",
    "Who would get lost using Google Maps?", 
    "Who would discover the secret of immortality first?",
    "Who would become a millionaire influencer?", 
    "Who would win a staring contest?",
    "Who would get abducted by aliens first?", 
    "Who would survive a cartoon-style free fall?",
    "Who would spend all their budget on useless things?", 
    "Who would win in a bar fight?",
    "Who would pass a college exam without studying?", 
    "Who would scare away ghosts in a haunted house?",
    "Who would become the leader of a mysterious cult?", 
    "Who is the luckiest?",
    "Who would win a strategic board game?", 
    "Who would be the worst babysitter?",
    "Who would get kicked out of a museum for touching the art?", 
    "Who could swim fastest against the current?",
    "Who would win a boxing match with official rules?", 
    "Who would climb Mount Everest in shorts?",
    "Who would create the craziest conspiracy theory?", 
    "Who would win an arm wrestling tournament?",
    "Who would be the best captain of a pirate ship?", 
    "Who would get banned from the internet first?",
    "Who would make the best Sunday barbecue?", 
    "Who would sleep through an earthquake?",
    "Who is more likely to become a superhero?", 
    "Who is more likely to become a supervillain?",
    "Who would win a sack race?", 
    "Who would solve a mystery like Sherlock Holmes?",
    "Who would get scammed easiest by a suspicious email?", 
    "Who is the best at bargaining at a flea market?",
    "Who would win a bad jokes contest?", 
    "Who would become the king of karaoke?",
    "Who could escape from a maximum security prison?", 
    "Who would write the best-selling fantasy novel?",
    "Who would end up on the cover of Time Magazine?", 
    "Who would be the first to scream 'Help!' seeing a spider?",
    "Who could convince a cat to obey them?", 
    "Who would win a poker game by bluffing?",
    "Who is the best at giving Christmas gifts?", 
    "Who would survive in the Sahara with only a bottle of water?",
    "Who would make the best cocktails at an open bar?", 
    "Who would invent the app of the century?",
    "Who would win a world video game championship?", 
    "Who would be mistaken for a celebrity on the street?",
    "Who could eat the spiciest chili without flinching?", 
    "Who is the worst driver?",
    "Who would spend hours explaining why their favorite series is the best?", 
    "Who would win a shouting match?",
    "Who would get kicked out of a cinema for spoiling the ending?", 
    "Who could fix an engine with duct tape and chewing gum?",
    "Who would do the best imitation of the other?", 
    "Who would spend Halloween night in a cemetery without fear?",
    "Who would win a medieval jousting duel?", 
    "Who would be elected mayor of your city?",
    "Who would finish the food supplies first in a bunker?", 
    "Who would become an urban legend?",
    "Who would win a pillow fight?", 
    "Who is the most chronically late?",
    "Who could walk on hot coals?", 
    "Who would be crowned king or queen of the jungle?",
    "Who would win a spelling bee?", 
    "Who would make the most absurd marriage proposal?",
    "Who would be chosen for a one-way space mission?", 
    "Who would spend hours in front of the mirror?",
    "Who would win a 48-hour TV series marathon?", 
    "Who would destroy modern art mistaking it for trash?",
    "Who would go grocery shopping and forget half the list?", 
    "Who would become the best private detective in town?",
    "Who could get a stranger to buy them dinner?", 
    "Who would win a snowball fight?",
    "Who would be the worst contestant on a TV quiz show?", 
    "Who would be saved first in a shipwreck?",
    "Who could stay silent for 24 hours straight?"
  ]
};

export const poolContenders: Record<Language, string[]> = {
  it: [
    "Giulio_Cesare", "Napoleone_Bonaparte", "Cleopatra", "Albert_Einstein", "Alessandro_Magno", "Marie_Curie", "Leonardo_da_Vinci", "Giovanna_d'Arco", "Gengis_Khan", "Dante_Alighieri", "Socrate", "Platone", "Aristotele", "Marco_Aurelio", "Spartaco", "Galileo_Galilei", "Isaac_Newton", "Charles_Darwin", "Nikola_Tesla", "Thomas_Edison", "Marco_Polo", "Cristoforo_Colombo", "Mahatma_Gandhi", "Winston_Churchill", "Abraham_Lincoln", "George_Washington", "Carlo_Magno", "Attila", "Saladino", "Ercole", "Achille", "Ulisse", "Zeus", "Ade_(divinità)", "Poseidone", "Atena", "Ares", "Thor_(mitologia)", "Odino", "Loki", "Re_Artù", "Robin_Hood", "William_Shakespeare", "Wolfgang_Amadeus_Mozart", "Ludwig_van_Beethoven", "Vincent_van_Gogh", "Pablo_Picasso", "Sun_Tzu", "Leonida_I", "Boudicca", "Caterina_II_di_Russia", "Elisabetta_I_d'Inghilterra", "Tutankhamon", "Ramses_II", "Hammurabi", "Confucio", "Gautama_Buddha", "Francesco_d'Assisi", "Amelia_Earhart", "Neil_Armstrong", "Juri_Gagarin", "Augusto", "Nerone", "Traiano", "Adriano", "Riccardo_I_d'Inghilterra", "Enrico_VIII_d'Inghilterra", "Luigi_XIV_di_Francia", "Maximilien_de_Robespierre", "Sherlock_Holmes", "Conte_Dracula", "Mostro_di_Frankenstein", "Leone", "Tigre", "Squalo_bianco", "Tyrannosaurus_rex", "Orso_grizzly", "Elefante", "Gorilla", "Aquila_reale", "Ghepardo", "Lupo_grigio", "Coccodrillo", "Orca", "Delfino", "Ippopotamo", "Rinoceronte", "Giraffa", "Canguro", "Koala", "Panda_gigante", "Unicorno", "Fenice_(mitologia)", "Pegaso", "Minotauro", "Centauro", "Cerbero", "Sfinge", "Grifone", "Medusa_(mitologia)"
  ],
  en: [
    "Julius_Caesar", "Napoleon", "Cleopatra", "Albert_Einstein", "Alexander_the_Great", "Marie_Curie", "Leonardo_da_Vinci", "Joan_of_Arc", "Genghis_Khan", "Dante_Alighieri", "Socrates", "Plato", "Aristotle", "Marcus_Aurelius", "Spartacus", "Galileo_Galilei", "Isaac_Newton", "Charles_Darwin", "Nikola_Tesla", "Thomas_Edison", "Marco_Polo", "Christopher_Columbus", "Mahatma_Gandhi", "Winston_Churchill", "Abraham_Lincoln", "George_Washington", "Charlemagne", "Attila", "Saladin", "Heracles", "Achilles", "Odysseus", "Zeus", "Hades", "Poseidon", "Athena", "Ares", "Thor", "Odin", "Loki", "King_Arthur", "Robin_Hood", "William_Shakespeare", "Mozart", "Beethoven", "Vincent_van_Gogh", "Pablo_Picasso", "Sun_Tzu", "Leonidas_I", "Boudica", "Catherine_the_Great", "Elizabeth_I", "Tutankhamun", "Ramesses_II", "Hammurabi", "Confucius", "Buddha", "Francis_of_Assisi", "Amelia_Earhart", "Neil_Armstrong", "Yuri_Gagarin", "Augustus", "Nero", "Trajan", "Hadrian_(_emperor_)", "Richard_I_of_England", "Henry_VIII", "Louis_XIV", "Maximilien_Robespierre", "Sherlock_Holmes", "Count_Dracula", "Frankenstein's_monster", "Lion", "Tiger", "Great_white_shark", "Tyrannosaurus", "Grizzly_bear", "Elephant", "Gorilla", "Golden_eagle", "Cheetah", "Wolf", "Crocodile", "Killer_whale", "Dolphin", "Hippopotamus", "Rhinoceros", "Giraffe", "Kangaroo", "Koala", "Giant_panda", "Unicorn", "Phoenix_(mythology)", "Pegasus", "Minotaur", "Centaur", "Cerberus", "Sphinx", "Gryphon", "Medusa"
  ]
};

export const poolTerrains: Record<Language, string[]> = {
  it: [
    "Tundra", "Luna", "Fossa_delle_Marianne", "Monte_Everest", "Foresta_amazzonica", "Palude", "Vulcano", "Antartide", "Ghiacciaio", "Siberia", "Grand_Canyon", "Barriera_corallina", "Isola_deserta", "Isola_di_Pasqua", "Madagascar", "Groenlandia", "Islanda", "Deserto_del_Sahara", "Deserto_del_Gobi", "Colosseo", "Piramidi_di_Giza", "Stonehenge", "Atlantide", "Pompei", "Acropoli_di_Atene", "Partenone", "Machu_Picchu", "Petra", "Grande_muraglia_cinese", "Cremlino_di_Mosca", "Torre_di_Londra", "Castello_di_Neuschwanstein", "Castello_medievale", "Fortezza", "Arena", "Torre_Eiffel", "Statua_della_Libertà", "Ponte_di_Brooklyn", "Central_Park", "Times_Square", "Sydney_Opera_House", "Piazza_San_Marco", "Piazza_Rossa", "Canal_Grande_(Venezia)", "Stazione_Spaziale_Internazionale", "Marte", "Nave_pirata", "Bunker", "Portaerei", "Monte_Bianco", "Monte_Fuji", "Kilimangiaro", "Vesuvio", "Etna", "Roma", "Milano", "Venezia", "Firenze", "Napoli", "Lago_di_Como"
  ],
  en: [
    "Tundra", "Moon", "Mariana_Trench", "Mount_Everest", "Amazon_rainforest", "Swamp", "Volcano", "Antarctica", "Glacier", "Siberia", "Grand_Canyon", "Coral_reef", "Desert_island", "Easter_Island", "Madagascar", "Greenland", "Iceland", "Sahara", "Gobi_Desert", "Colosseum", "Egyptian_pyramids", "Stonehenge", "Atlantis", "Pompeii", "Acropolis_of_Athens", "Parthenon", "Machu_Picchu", "Petra", "Great_Wall_of_China", "Moscow_Kremlin", "Tower_of_London", "Neuschwanstein_Castle", "Medieval_castle", "Fortress", "Arena", "Eiffel_Tower", "Statue_of_Liberty", "Brooklyn_Bridge", "Central_Park", "Times_Square", "Sydney_Opera_House", "Piazza_San_Marco", "Red_Square", "Grand_Canal_(_Venice_)", "International_Space_Station", "Mars", "Pirate_ship", "Bunker", "Aircraft_carrier", "Mont_Blanc", "Mount_Fuji", "Kilimanjaro", "Mount_Vesuvius", "Mount_Etna", "Rome", "Milan", "Venice", "Florence", "Naples", "Lake_Como"
  ]
};

export const poolEquipment: Record<Language, string[]> = {
  it: [
    "Spada_laser", "Padella", "Mjöllnir", "Coltello_svizzero", "Bacchetta_magica", "Banana", "Lanciafiamme", "Corda", "Estintore", "Arco_(arma)", "Grimorio", "Tostapane", "Martello_(utensile)", "Ombrello", "Lanterna", "Pala_(attrezzo)", "Bussola_(strumento)", "Smartphone", "Skateboard", "Chitarra_elettrica", "Dinamite", "Forbici", "Frusta", "Megafono", "Binocolo", "Zaino", "Spada", "Scudo_(armatura)", "Clava", "Lancia_(arma)", "Ascia", "Balestra", "Fionda", "Catapulta", "Cannone", "Fucile", "Pistola", "Granata_(arma)", "Bazooka", "Coltello", "Katana", "Nunchaku", "Boomerang", "Tomahawk", "Chakram", "Kukri", "Scimitarra", "Teiera", "Specchio", "Sega_(_utensile_)", "Sveglia", "Lente_d'ingrandimento", "Microscopio", "Telescopio", "Astrolabio", "Orologio_da_tasca", "Clessidra", "Candela", "Accendino", "Torcia"
  ],
  en: [
    "Lightsaber", "Frying_pan", "Mjöllnir", "Swiss_Army_knife", "Magic_wand", "Banana", "Flame-thrower", "Rope", "Fire_extinguisher", "Bow_and_arrow", "Grimoire", "Toaster", "Hammer", "Umbrella", "Lantern", "Shovel", "Compass", "Smartphone", "Skateboard", "Electric_guitar", "Dynamite", "Scissors", "Whip", "Megaphone", "Binoculars", "Backpack", "Sword", "Shield", "Club", "Spear", "Axe", "Crossbow", "Slingshot", "Catapult", "Cannon", "Rifle", "Pistol", "Grenade", "Bazooka", "Knife", "Katana", "Nunchaku", "Boomerang", "Tomahawk", "Chakram", "Kukri", "Scimitar", "Teapot", "Mirror", "Saw", "Alarm_clock", "Magnifying_glass", "Microscope", "Telescope", "Astrolabe", "Pocket_watch", "Hourglass", "Candle", "Lighter", "Flashlight"
  ]
};
